### ISSUE TITLE
Problem with installation on Windows

### ISSUE THREAD

**Issue by CBornes** [elcorto/pwtools#4]
I'm trying to install Pwtools on Windows and I'm having a hard time

I've installed Pwtool using

```
git clone https://github.com/elcorto/pwtools.git
pip install -e pwtools
```

Everything went well, at least no errors. But when I try to run 

 ```
from pwtools import io
from ase.visualize import view

traj = io.read_cp2k_md('zeo_opti.log')
view(traj)`
```

I get the following error

`cannot import name '_flib' from 'pwtools' (c:\users\cb\pwtools\pwtools\__init__.py)`

Is there a way to troubleshoot this?

**Comment by elcorto** [comment]
@CBornes if you found a solution to build on Windows, feel free to share that here as future reference for other users. 

You might also consider replacing the extension-dependent parts of the parser you plan on using with slower numpy-only code. That is pretty straight forward, but I don't have the time and need to implement and test that at the moment, unfortunately. PRs are always welcome!

Since there was no feedback on the info I gave above, I'm taking the liberty to close this one. Feel free to re-open. Thanks for reporting!
